// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"Go-000/Week04/internal/conf"
	http2 "Go-000/Week04/internal/server/http"
	"Go-000/Week04/internal/service"
	"net/http"
)

// Injectors from init.go:

func InitializeServer(config conf.Config, web *http.Server) *http2.WebServer {
	service := initService(config)
	httpWebServer := initHttp(service, web)
	return httpWebServer
}

// init.go:

func initService(config conf.Config) *service.Service {
	svr := service.New(config)
	return svr
}

func initHttp(svr *service.Service, web *http.Server) *http2.WebServer {
	return http2.New(svr, web)
}
